#ibmi-install-nodejs.yml 
#Refer to https://bitbucket.org/ibmi/opensource/src/master/docs/yum/ to get more details about IBM i opensource.  
---
- hosts: ibmi 
  gather_facts: no

  vars:
    demo_file_with_path_on_local:
    temp_dir_on_target: 
  
  environment:
    QIBM_MULTI_THREADED: 'Y'

  tasks:
  - name: Install Node js
    command: /QOpensys/pkgs/bin/yum install nodejs10 -y
    ignore_errors: True

  - name: copy file to target IFS directory
    copy: src='{{ demo_file_with_path_on_local }}' dest={{ temp_dir_on_target }}
    ignore_errors: True
    when: "'CPF3606' not in check_prodct_result.stderr"

  - name: Put the demo application code
    command: tar -xf {{temp_dir_on_target }}/mynodeapp.tar -C {{ temp_dir_on_target }} 

  - name: npm i
    shell: "(/QOpensys/pkgs/lib/nodejs10/bin/npm  i  --scripts-prepend-node-path)"
    args:
      warn: False
      chdir: {{temp_dir_on_target }}/mynodeapp
      executable: /usr/bin/sh

  - name: Start the demo application
    shell: "(nohup /QOpensys/pkgs/lib/nodejs10/bin/node {{temp_dir_on_target }}/mynodeapp/index.js >/dev/null 2>&1 &)"
    args:
      warn: False
      chdir: /home/Ansible/mynodeapp
      executable: /usr/bin/sh
    async: 10